export const MAX_LIVES = 3

export const TaskDescriptionType = {
  Formula: 'formula',
  Text: 'text',
  TextInline: 'textInline',
  Comparison: 'comparison',
  ColumnOperation: 'columnOperation',
  Test: 'test',
  Equation: 'equation',
  Complex: 'complex',
  CoordinatePlane: 'coordinatePlane',
  Table: 'table',
  CoordinatePlane3D: 'coordinatePlane3D',
  TrigonometryCoordinatePlane: 'trigonometryCoordinatePlane',
  CalculateByImage: 'calculateByImage',
  CalculateByImageWithCell: 'calculateByImageWithCell',
  AnswerCell: 'answerCell',
  Drawing: 'drawing',
  Audio: 'audio',
  Coloring: 'coloring',
  MatchingWithDragging: 'matchingWithDragging',
  MatchingTask: 'matchingTask',
  OrderByLine: 'orderByLine',
  Image: 'image',
  HandwritingRecognition: 'handwritingRecognition',
  FrequencyPolygon: 'frequencyPolygon',
  FrequencyHistogram: 'frequencyHistogram',
  TableMultipleChoice: 'tableMultipleChoice',
  CubeCalculator: 'cubeCalculator',
}

export const TASK_DESCRIPTIONS_WITHOUT_CALC = [
  TaskDescriptionType.Test,
  // Comparison uses MathInput in the new trainer — needs the on-screen calc.
  TaskDescriptionType.CoordinatePlane,
  TaskDescriptionType.CalculateByImage,
  TaskDescriptionType.CalculateByImageWithCell,
  TaskDescriptionType.MatchingWithDragging,
  TaskDescriptionType.Coloring,
  TaskDescriptionType.Image,
  TaskDescriptionType.MatchingTask,
  TaskDescriptionType.HandwritingRecognition,
  TaskDescriptionType.TableMultipleChoice,
]
