import type { Meta, StoryObj } from '@storybook/react-vite'

import {
  HIDDEN_TASK_ARGTYPES,
  STORY_DOCS,
  storyDocs,
  templateDocs,
} from '../../../shared/storybook/story-docs'
import {
  getGroupControlOptions,
  pickOperationFixture,
  renderAllOperationsStory,
  renderDefaultStory,
  renderOperationStory,
  renderWithSolutionStory,
  type ColumnOperationStoryMetaArgs,
  type OperationFixture,
  type TemplateGroupFixture,
  getOpenInTrainerControls,
  normalizeAllTasksFile,
  type AllTasksFile,
} from '../../lib/storybook'
import type { ColumnOperationTask } from '../../lib/types.task'

import allTasksJson from './data/all-tasks.json'
import groupsJson from './data/groups.json'
import operationsJson from './data/operations.json'
import fixture from './data/task.json'
import readme from './README.md?raw'

import { ColumnOperationPlain as Template } from '.'

const task = fixture as unknown as ColumnOperationTask
const groups = groupsJson as unknown as TemplateGroupFixture[]
const operations = operationsJson as unknown as OperationFixture[]
const { groupIds, defaultGroup } = getGroupControlOptions(groups)
const allTasks = allTasksJson as unknown as AllTasksFile
const normalizedTasks = normalizeAllTasksFile(allTasks)
const openInTrainer = getOpenInTrainerControls(groups)

const ROOT_TITLE = 'Templates/ColumnOperation/plain'

const meta = {
  title: 'Templates/ColumnOperation/plain',
  component: Template,
  args: {
    group: defaultGroup,
    taskId: openInTrainer.defaultTaskId,
  },
  argTypes: {
    ...HIDDEN_TASK_ARGTYPES,
    group: {
      control: 'select',
      options: groupIds,
      description:
        'Операция из data/groups.json: plus / minus / times / div (`all` — все в AllGroups)',
    },
    taskId: {
      control: 'select',
      options: openInTrainer.allTaskIds,
      description: 'Конкретная задача (id) из all-tasks.json',
    },
  },
  parameters: templateDocs(readme),
} satisfies Meta<ColumnOperationStoryMetaArgs>

export default meta
type Story = StoryObj<ColumnOperationStoryMetaArgs>

export const Default: Story = {
  parameters: storyDocs(STORY_DOCS.default),
  render: ({ group, taskId }) =>
    renderDefaultStory({
      Template,
      groups,
      fallbackTask: task,
      group,
      taskId,
      allTasks,
      grade: normalizedTasks.defaultGrade,
      rootTitle: ROOT_TITLE,
    }),
}

export const WithSolution: Story = {
  parameters: storyDocs(STORY_DOCS.withSolution),
  render: ({ group, taskId }) =>
    renderWithSolutionStory({
      Template,
      groups,
      fallbackTask: task,
      group,
      taskId,
      allTasks,
      grade: normalizedTasks.defaultGrade,
      rootTitle: ROOT_TITLE,
    }),
}

export const Addition: Story = {
  render: () =>
    renderOperationStory({
      Template,
      fixture: pickOperationFixture(operations, 'plus'),
    }),
}

export const Subtraction: Story = {
  render: () =>
    renderOperationStory({
      Template,
      fixture: pickOperationFixture(operations, 'minus'),
    }),
}

export const Multiplication: Story = {
  render: () =>
    renderOperationStory({
      Template,
      fixture: pickOperationFixture(operations, 'times'),
    }),
}

export const Division: Story = {
  render: () =>
    renderOperationStory({
      Template,
      fixture: pickOperationFixture(operations, 'div'),
    }),
}

/**
 * Reproduces the reported production bug (lessonId 2105, 86809 ÷ 2): a
 * dividend that needs a bring-down + carry (43404, remainder 1) rather than
 * the base `div` fixture's exact/no-remainder case (90000 ÷ 2). Cloned from
 * the `div` fixture with dividend/answer overridden inline — do not hand-edit
 * `operations.json`, it's generated by `generate-column-operation-template-groups.mjs`.
 */
const divisionLongCarryFixture: OperationFixture | undefined = (() => {
  const base = pickOperationFixture(operations, 'div')
  if (!base) return undefined

  const replaceDividend = (value: unknown): unknown =>
    typeof value === 'string' ? value.replaceAll('90000', '86809') : value

  return {
    ...base,
    task: {
      ...base.task,
      fields: { ...base.task.fields, number1: 86809 },
      description: {
        ...base.task.description,
        content: Object.fromEntries(
          Object.entries(
            base.task.description.content as Record<string, unknown>,
          ).map(([locale, value]) => [locale, replaceDividend(value)]),
        ),
      },
      solution:
        base.task.solution && typeof base.task.solution === 'object'
          ? {
              ...base.task.solution,
              answer:
                base.task.solution.answer &&
                typeof base.task.solution.answer === 'object'
                  ? { ...base.task.solution.answer, rus: '43404' }
                  : base.task.solution.answer,
            }
          : base.task.solution,
    },
  } as OperationFixture
})()

export const DivisionLongCarry: Story = {
  render: () =>
    renderOperationStory({
      Template,
      fixture: divisionLongCarryFixture,
      withSolution: true,
    }),
}

export const AllOperations: Story = {
  render: () => renderAllOperationsStory({ Template, fixtures: operations }),
}
