import { createRoot } from 'react-dom/client'

import type { TaskModalProps } from './modules/task-modal/model/types/props'
import { TaskModal } from './modules/task-modal/task-modal'

// Mock dependencies
const mockDependencies = {
  api: {
    urlByCompany: () => '',
    urlByLanguage: () => '',
    sendToSeshat: () => Promise.resolve({}),
    getUserRating: () => Promise.resolve({}),
    getScienceAcademyPupilsRating: () => Promise.resolve({}),
    getRating: () => Promise.resolve({}),
    updatePayoutStatus: () => Promise.resolve({}),
    getCoursesList: () => Promise.resolve({}),
    getCourseChapters: () => Promise.resolve({}),
    refreshUserSession: () => Promise.resolve({}),
    getTasksByLessonId: () => Promise.resolve({}),
    getCheckTasksByLessonId: () => Promise.resolve({}),
    getUntDiagnosticTasksByLessonIds: () => Promise.resolve({}),
    getPupilUntDiagnostics: () => Promise.resolve({}),
    skipUserUntDiagnostics: () => Promise.resolve({}),
    deleteUserUntDiagnostics: () => Promise.resolve({}),
    getTasksByControlWorkId: () => Promise.resolve({}),
    getTasksByUserLessonId: () => Promise.resolve({}),
    getTasksByUserCheckLessonId: () => Promise.resolve({}),
    getTasksByPersonalStudyItemId: () => Promise.resolve({}),
    getTaskSolution: () => Promise.resolve({}),
    getVideoExplanation: () => Promise.resolve({}),
    getVideoExplanationForControlWork: () => Promise.resolve({}),
    checkAnswer: () => Promise.resolve({}),
    login: () => Promise.resolve({}),
    loginByParentPhoneNumber: () => Promise.resolve({}),
    register: () => Promise.resolve({}),
    freeSubscriptionRegister: () => Promise.resolve({}),
    acceptTerms: () => Promise.resolve({}),
    isAcceptedTerms: () => Promise.resolve({}),
    getLastUserActions: () => Promise.resolve({}),
    getLastUserActionsOfSubscribedPupils: () => Promise.resolve({}),
    getSubscribedPupils: () => Promise.resolve({}),
    getSubscribedNewPupils: () => Promise.resolve({}),
    getUserActionsBySearchText: () => Promise.resolve({}),
    getCurrentMentorSessions: () => Promise.resolve({}),
    getSessionsBySearchText: () => Promise.resolve({}),
    isMentorAssigned: () => Promise.resolve({}),
    getLastUserActionsOfDiagnosticsLessons: () => Promise.resolve({}),
    getLastUserActionsOfPaidPupils: () => Promise.resolve({}),
    getUserActionsByDateRange: () => Promise.resolve({}),
    getLessonById: () => Promise.resolve({}),
    getUserActionById: () => Promise.resolve({}),
    addCoinForTheory: () => Promise.resolve({}),
    getTeacherList: () => Promise.resolve({}),
    getB2BTeacherList: () => Promise.resolve({}),
    getB2BTeachersByInstitutionStatus: () => Promise.resolve({}),
    getB2BTeachersByInstitutionId: () => Promise.resolve({}),
    getSchoolTeacherList: () => Promise.resolve({}),
    getSanSchoolTeacherData: () => Promise.resolve({}),
    getSanSchoolPupilDiagnosticList: () => Promise.resolve({}),
    getPupilList: () => Promise.resolve({}),
    getCurrentEmployeeAssignedPupilList: () => Promise.resolve({}),
    getEmployeeAssignedPupilListByEmployeeId: () => Promise.resolve({}),
    changeEmployeeAssignedPupilStatus: () => Promise.resolve({}),
    editEmployeeIdsOnAssignedMobilePupils: () => Promise.resolve({}),
    getPupilMobileStatusBySearchText: () => Promise.resolve({}),
    getPupilMobileStatisticByDepartment: () => Promise.resolve({}),
    getPupilMobileByDate: () => Promise.resolve({}),
    getPupilProfileData: () => Promise.resolve({}),
    getOurPupilsBySearchText: () => Promise.resolve({}),
    getOurPupils: () => Promise.resolve({}),
    saveTeacher: () => Promise.resolve({}),
    saveTeacherProfile: () => Promise.resolve({}),
    addTeacher: () => Promise.resolve({}),
    changeUserPassword: () => Promise.resolve({}),
    savePupil: () => Promise.resolve({}),
    saveB2BPupilData: () => Promise.resolve({}),
    savePupilByTeacher: () => Promise.resolve({}),
    addPupil: () => Promise.resolve({}),
    changePupilPreparationMinTaskQuantity: () => Promise.resolve({}),
    addPupilByTeacher: () => Promise.resolve({}),
    bindTeacherToPupil: () => Promise.resolve({}),
    unbindTeacherFromPupil: () => Promise.resolve({}),
    deletePupil: () => Promise.resolve({}),
    deleteB2BPupil: () => Promise.resolve({}),
    restorePupil: () => Promise.resolve({}),
    getInstitutionList: () => Promise.resolve({}),
    addInstitution: () => Promise.resolve({}),
    saveInstitution: () => Promise.resolve({}),
    addClass: () => Promise.resolve({}),
    saveClass: () => Promise.resolve({}),
    saveControlWorkTaskUserAnswer: () => Promise.resolve({}),
    saveCheckLessonTaskUserAnswer: () => Promise.resolve({}),
    setControlWorkAsFinished: () => Promise.resolve({}),
    setCheckLessonAsFinished: () => Promise.resolve({}),
    getRegions: () => Promise.resolve({}),
    getDistricts: () => Promise.resolve({}),
    getInstitutions: () => Promise.resolve({}),
    getDistrictTeacherList: () => Promise.resolve({}),
    getTeacherPupils: () => Promise.resolve({}),
    getCurrentTeacherGroupedPupils: () => Promise.resolve({}),
    getCurrentTeacherPupils: () => Promise.resolve({}),
    getCurrentTeacherInfo: () => Promise.resolve({}),
    getCurrentManagerProgressInfo: () => Promise.resolve({}),
    getManagersProgressInfo: () => Promise.resolve({}),
    getInstitutionById: () => Promise.resolve({}),
    getClassById: () => Promise.resolve({}),
    getLessons: () => Promise.resolve({}),
    getUserLessons: () => Promise.resolve({}),
    getGroupedControlWorks: () => Promise.resolve({}),
    assignControlWork: () => Promise.resolve({}),
    getCurrentTeacherControlWorks: () => Promise.resolve({}),
    getCsvNewPayments: () => Promise.resolve({}),
    cancelControlWork: () => Promise.resolve({}),
    restoreControlWork: () => Promise.resolve({}),
    getControlWorkStatuses: () => Promise.resolve({}),
    getTeacherPupilsReport: () => Promise.resolve({}),
    getTeacherPupilsRating: () => Promise.resolve({}),
    getUnitsWithLessons: () => Promise.resolve({}),
    getChaptersWithLessons: () => Promise.resolve({}),
    getTaskListForExport: () => Promise.resolve({}),
    getTestTaskByGrade: () => Promise.resolve({}),
    getTaskByType: () => Promise.resolve({}),
    getPupilsLastActionAt: () => Promise.resolve({}),
    getTeacherByCode: () => Promise.resolve({}),
    bindCurrentUserToTeacherByCode: () => Promise.resolve({}),
    unbindPupilFromCurrentTeacher: () => Promise.resolve({}),
    getSolutionByUserActionId: () => Promise.resolve({}),
    getSolutionByTaskFields: () => Promise.resolve({}),
    saveCurrentPupilProfile: () => Promise.resolve({}),
    getCurrentPupilGrade: () => Promise.resolve({}),
    getCurrentPupilInstitution: () => Promise.resolve({}),
    saveCurrentTeacherProfile: () => Promise.resolve({}),
    getCurrentPupilTeachers: () => Promise.resolve({}),
    getTeachersByInstitutionId: () => Promise.resolve({}),
    updatePassword: () => Promise.resolve({}),
    sendConfirmationCodeForRestorePassword: () => Promise.resolve({}),
    sendConfirmationCodeForRegistration: () => Promise.resolve({}),
    sendConfirmationCodeForCashback: () => Promise.resolve({}),
    restorePassword: () => Promise.resolve({}),
    getSelfWorks: () => Promise.resolve({}),
    getInstitutionsOrTeachers: () => Promise.resolve({}),
    sendMessagesAboutNonFinishedSelfWorks: () => Promise.resolve({}),
    getSelfWorksByGroupId: () => Promise.resolve({}),
    createSelfWorks: () => Promise.resolve({}),
    getSelfWorkStatuses: () => Promise.resolve({}),
    getPupilSelfWorks: () => Promise.resolve({}),
    cancelSelfWork: () => Promise.resolve({}),
    restoreSelfWork: () => Promise.resolve({}),
    getPenaltySelfWork: () => Promise.resolve({}),
    getCurrentTeacherLessons: () => Promise.resolve({}),
    saveTeacherLesson: () => Promise.resolve({}),
    getPreviewTasksByLessonId: () => Promise.resolve({}),
    getLearnTasksByTeacherLessonId: () => Promise.resolve({}),
    getCheckTasksByTeacherLessonId: () => Promise.resolve({}),
    getTeacherLessonById: () => Promise.resolve({}),
    getGroupList: () => Promise.resolve({}),
    createGroup: () => Promise.resolve({}),
    saveGroup: () => Promise.resolve({}),
    getGroupPupils: () => Promise.resolve({}),
    getEducationCenterPupils: () => Promise.resolve({}),
    searchPupils: () => Promise.resolve({}),
    searchUsers: () => Promise.resolve({}),
    searchParents: () => Promise.resolve({}),
    updateParentId: () => Promise.resolve({}),
    searchEmployee: () => Promise.resolve({}),
    searchFeedbacks: () => Promise.resolve({}),
    searchPayments: () => Promise.resolve({}),
    searchActiveSubscriptions: () => Promise.resolve({}),
    searchLastPayments: () => Promise.resolve({}),
    searchLastSanSchoolPayments: () => Promise.resolve({}),
    addPupilToGroup: () => Promise.resolve({}),
    removePupilFromGroup: () => Promise.resolve({}),
    getEducationCenterTeachers: () => Promise.resolve({}),
    callToPupil: () => Promise.resolve({}),
    callToParent: () => Promise.resolve({}),
    audioCall: () => Promise.resolve({}),
    getPaymentList: () => Promise.resolve({}),
    getPaymentListByFilter: () => Promise.resolve({}),
    getManagerPayments: () => Promise.resolve({}),
    getManagersSuperBonuses: () => Promise.resolve({}),
    addPayment: () => Promise.resolve({}),
    addPaymentWithoutCheck: () => Promise.resolve({}),
    addPrePayment: () => Promise.resolve({}),
    editPrePayment: () => Promise.resolve({}),
    editPayment: () => Promise.resolve({}),
    getPaymentByChangeRequestId: () => Promise.resolve({}),
    getPaymentChangeRequestsList: () => Promise.resolve({}),
    requestToEditPayment: () => Promise.resolve({}),
    AcceptPaymentChangeRequest: () => Promise.resolve({}),
    AcceptPaymentChangeRequestByFinancier: () => Promise.resolve({}),
    RefusePaymentChangeRequest: () => Promise.resolve({}),
    addAutoPaymentProblemSolution: () => Promise.resolve({}),
    getPayoutList: () => Promise.resolve({}),
    getPayoutsByUserId: () => Promise.resolve({}),
    addPayout: () => Promise.resolve({}),
    getRewardList: () => Promise.resolve({}),
    addReward: () => Promise.resolve({}),
    editReward: () => Promise.resolve({}),
    getCommentList: () => Promise.resolve({}),
    addComment: () => Promise.resolve({}),
    patchCommentEmployeeAssignedPupil: () => Promise.resolve({}),
    deleteComment: () => Promise.resolve({}),
    editComment: () => Promise.resolve({}),
    finishStudyActivity: () => Promise.resolve({}),
    buySubscription: () => Promise.resolve({}),
    checkSubscription: () => Promise.resolve({}),
    getCurrentTeacherTaskFolders: () => Promise.resolve({}),
    saveTeacherOwnTask: () => Promise.resolve({}),
    getTeacherTasksByFolderId: () => Promise.resolve({}),
    getTeacherOwnTaskByTaskId: () => Promise.resolve({}),
    previewGeneratedTask: () => Promise.resolve({}),
    getChatMessages: () => Promise.resolve({}),
    getLastChatMessages: () => Promise.resolve({}),
    getChatMessagesRange: () => Promise.resolve({}),
    getChatMessagesCount: () => Promise.resolve({}),
    sendChatMessage: () => Promise.resolve({}),
    sendChatMessageToPupil: () => Promise.resolve({}),
    sendTemplateToPupil: () => Promise.resolve({}),
    sendEvaluationTemplate: () => Promise.resolve({}),
    sendEvaluationTemplateToParent: () => Promise.resolve({}),
    sendTemplateToParent: () => Promise.resolve({}),
    getWhatsappTemplates: () => Promise.resolve({}),
    getWhatsappMessagesByPage: () => Promise.resolve({}),
    sendVoiceMessageToPupil: () => Promise.resolve({}),
    setCurrentPupilChatMessagesAsRead: () => Promise.resolve({}),
    getParentChatMessages: () => Promise.resolve({}),
    getLastParentChatMessages: () => Promise.resolve({}),
    getParentChatMessagesRange: () => Promise.resolve({}),
    getParentChatMessagesCount: () => Promise.resolve({}),
    editMlLogActualTag: () => Promise.resolve({}),
    sendChatMessageToParent: () => Promise.resolve({}),
    addUserLastSolvingTask: () => Promise.resolve({}),
    addOrEditTaskVideo: () => Promise.resolve({}),
    getDiagnosticsLessons: () => Promise.resolve({}),
    getGeometryLessonsFunnelPage: () => Promise.resolve({}),
    registerOnStartGeometryTasks: () => Promise.resolve({}),
    getUpcomingYearTasksFunnelPage: () => Promise.resolve({}),
    registerOnStartUpcomingYearTasks: () => Promise.resolve({}),
    getDiagnosticLessonByLessonId: () => Promise.resolve({}),
    getMentorDiagnostic: () => Promise.resolve({}),
    getDiagnosticsLessonsReference: () => Promise.resolve({}),
    diagnosticsCheckAnswer: () => Promise.resolve({}),
    diagnosticsShowSolution: () => Promise.resolve({}),
    getDiagnosticsSummary: () => Promise.resolve({}),
    getPupilDiagnosticsSummary: () => Promise.resolve({}),
    getCurrentTeacherDiagnosticsLessons: () => Promise.resolve({}),
    getPersonalStudyItems: () => Promise.resolve({}),
    addPersonalStudyItem: () => Promise.resolve({}),
    getExistsFreezingToday: () => Promise.resolve({}),
    removePersonalStudyItem: () => Promise.resolve({}),
    finishPersonalStudyItem: () => Promise.resolve({}),
    getPersonalStudyChangeRequestsByLanguage: () => Promise.resolve({}),
    getPersonalStudyChangeRequestsByStatusAndByLanguage: () =>
      Promise.resolve({}),
    refusedPersonalStudyRequest: () => Promise.resolve({}),
    changePersonalStudyFromRequest: () => Promise.resolve({}),
    addUntPersonalStudyTasks: () => Promise.resolve({}),
    getUntPersonalStudyTasks: () => Promise.resolve({}),
    deleteUntPersonalStudyTasks: () => Promise.resolve({}),
    editUntPersonalStudyTasks: () => Promise.resolve({}),
    rearrangeUntPersonalStudyTasks: () => Promise.resolve({}),
    getCurrentTeacherPersonalStudyItems: () => Promise.resolve({}),
    getMissedTasks: () => Promise.resolve({}),
    getCurrentMathematicsLessons: () => Promise.resolve({}),
    getB2BPupilPlanProgress: () => Promise.resolve({}),
    checkIsUserB2BPupil: () => Promise.resolve({}),
    getPersonalStudyRating: () => Promise.resolve({}),
    getPersonalStudyCashback: () => Promise.resolve({}),
    getCashbackSummary: () => Promise.resolve({}),
    getPersonalStudyPupilList: () => Promise.resolve({}),
    getIrregularPupilList: () => Promise.resolve({}),
    addHandligBackwardPupilStatus: () => Promise.resolve({}),
    getConsecutiveUnexecutedPupilList: () => Promise.resolve({}),
    getPersonalStudiesGroupedByDate: () => Promise.resolve({}),
    getMobilePupilsKPI: () => Promise.resolve({}),
    getFilteredPersonalStudiesGroupedByDate: () => Promise.resolve({}),
    savePersonalStudyItem: () => Promise.resolve({}),
    savePersonalStudyItemNextTask: () => Promise.resolve({}),
    getPersonalItemsUnt: () => Promise.resolve({}),
    loadTelegramFile: () => Promise.resolve({}),
    loadFile: () => Promise.resolve({}),
    startKemelOlympiadFirstStageForAnonymous: () => Promise.resolve({}),
    startKemelOlympiadForAnonymous: () => Promise.resolve({}),
    startKemelOlympiadForAuthenticated: () => Promise.resolve({}),
    getTasksByOlympiadItemId: () => Promise.resolve({}),
    editUserIdOfOlympiadItem: () => Promise.resolve({}),
    getLastOlympiadInfo: () => Promise.resolve({}),
    getLastDiplomaImage: () => Promise.resolve({}),
    downloadUserLastDiploma: () => Promise.resolve({}),
    downloadUserCertificate: () => Promise.resolve({}),
    registerOnDiagnostics: () => Promise.resolve({}),
    getCashbackListByUserId: () => Promise.resolve({}),
    getLeftoverCashback: () => Promise.resolve({}),
    getKpi: () => Promise.resolve({}),
    getSalesKpi: () => Promise.resolve({}),
    getSalesWithReturn: () => Promise.resolve({}),
    getSalesByMonthOrInterval: () => Promise.resolve({}),
    getSalesBonuses: () => Promise.resolve({}),
    updateBonusCoefficients: () => Promise.resolve({}),
    getManagersSalesAmount: () => Promise.resolve({}),
    getManagersSalesAmountForTV: () => Promise.resolve({}),
    getCommandsMonthAmount: () => Promise.resolve({}),
    getContinuationStatistics: () => Promise.resolve({}),
    sendExplanationMessageToNewPupil: () => Promise.resolve({}),
    sendMessageToNewParent: () => Promise.resolve({}),
    sendMessageToNewParentMobile: () => Promise.resolve({}),
    sendExplanationMessageToNewPupilMobile: () => Promise.resolve({}),
    sendExplanationMessageToNewPupilTelegram: () => Promise.resolve({}),
    sendMessageToNewParentTelegram: () => Promise.resolve({}),
    sendTelegramMessageAboutPayment: () => Promise.resolve({}),
    sendMessageAboutPayment: () => Promise.resolve({}),
    sendUzbSmsToPupil: () => Promise.resolve({}),
    sendUzbSmsToParent: () => Promise.resolve({}),
    sendUzbOfferToParent: () => Promise.resolve({}),
    startFreeTasksAuthentication: () => Promise.resolve({}),
    getProctoringLink: () => Promise.resolve({}),
    startUnifiedNationalTest: () => Promise.resolve({}),
    checkLastDiagnosticCompletion: () => Promise.resolve({}),
    checkLastUntMockTestCompletion: () => Promise.resolve({}),
    getPupilUntMockTestsItems: () => Promise.resolve({}),
    getDataForPreparationStatistics: () => Promise.resolve({}),
    getPreparationStatisticsByUnits: () => Promise.resolve({}),
    sendCertificate: () => Promise.resolve({}),
    sendRequestForCashback: () => Promise.resolve({}),
    rejectCashback: () => Promise.resolve({}),
    acceptCashback: () => Promise.resolve({}),
    acceptCashbacks: () => Promise.resolve({}),
    sendCashbackRequest: () => Promise.resolve({}),
    getActiveCashbackRequestForCurrentUser: () => Promise.resolve({}),
    sendCashbackRequestByEmployee: () => Promise.resolve({}),
    getSalesReportGroupedBy: () => Promise.resolve({}),
    getManagerPaymentsbyDate: () => Promise.resolve({}),
    getManagerCashbackbyCompanyName: () => Promise.resolve({}),
    checkWhatsappNumber: () => Promise.resolve({}),
    getExpenses: () => Promise.resolve({}),
    addExpense: () => Promise.resolve({}),
    editExpense: () => Promise.resolve({}),
    getExpenseTypes: () => Promise.resolve({}),
    deleteExpense: () => Promise.resolve({}),
    sendDoCashbackRequest: () => Promise.resolve({}),
    getHunters: () => Promise.resolve({}),
    getUserHunterPins: () => Promise.resolve({}),
    addUserHunterPin: () => Promise.resolve({}),
    getHuntersWithEmployee: () => Promise.resolve({}),
    changeHunterActive: () => Promise.resolve({}),
    saveHunterSipuniId: () => Promise.resolve({}),
    addHunter: () => Promise.resolve({}),
    getHunterSalaryData: () => Promise.resolve({}),
    saveHunterWorkingDays: () => Promise.resolve({}),
    getCurrentUserHunterId: () => Promise.resolve({}),
    sendWebinarMessage: () => Promise.resolve({}),
    callToLeadByHunter: () => Promise.resolve({}),
    sendLiveWebinarMessage: () => Promise.resolve({}),
    addExcelLeads: () => Promise.resolve({}),
    addExcelLeadsToHunters: () => Promise.resolve({}),
    startDistributionWebinarLeads: () => Promise.resolve({}),
    startDistributionMobileLeads: () => Promise.resolve({}),
    getLeadsKpi: () => Promise.resolve({}),
    getLeadsCount: () => Promise.resolve({}),
    getManagers: () => Promise.resolve({}),
    getManagersByDepartment: () => Promise.resolve({}),
    getOnlyManagersByDepartment: () => Promise.resolve({}),
    getManagerWorkdays: () => Promise.resolve({}),
    getTodayManagers: () => Promise.resolve({}),
    addManagerWorkday: () => Promise.resolve({}),
    getFarmersByDepartment: () => Promise.resolve({}),
    getManagerByUserId: () => Promise.resolve({}),
    getActiveManagers: () => Promise.resolve({}),
    getPaymentHistory: () => Promise.resolve({}),
    getPaymentHistoryById: () => Promise.resolve({}),
    changeManagerActive: () => Promise.resolve({}),
    getSubscriptionList: () => Promise.resolve({}),
    getSubscriptionListByFilter: () => Promise.resolve({}),
    getSubscriptionById: () => Promise.resolve({}),
    getSubscriptionHistory: () => Promise.resolve({}),
    getSubscriptionHistoryById: () => Promise.resolve({}),
    addSubscription: () => Promise.resolve({}),
    editSubscription: () => Promise.resolve({}),
    addSubscriptionByManager: () => Promise.resolve({}),
    acceptPublishingSubscription: () => Promise.resolve({}),
    rejectPublishingSubscription: () => Promise.resolve({}),
    acceptSubscription: () => Promise.resolve({}),
    rejectSubscription: () => Promise.resolve({}),
    changeSubscriptionSbbEmployeeUserId: () => Promise.resolve({}),
    getSubscriptionNewPayments: () => Promise.resolve({}),
    getNewPayments: () => Promise.resolve({}),
    getNewPaymentById: () => Promise.resolve({}),
    getRelativeSubscriptionRequestsByStatuses: () => Promise.resolve({}),
    addNewPayment: () => Promise.resolve({}),
    editNewPayment: () => Promise.resolve({}),
    editNewPaymentsSipuni: () => Promise.resolve({}),
    acceptNewPayment: () => Promise.resolve({}),
    rejectNewPayment: () => Promise.resolve({}),
    getUnusedNewPaymentsByManager: () => Promise.resolve({}),
    isNewPaymentUsedInSubscription: () => Promise.resolve({}),
    getSubscriptionChangeRequests: () => Promise.resolve({}),
    getSubscriptionChangeRequestBySearchText: () => Promise.resolve({}),
    addSubscriptionChangeRequest: () => Promise.resolve({}),
    getSubscriptionChangeRequest: () => Promise.resolve({}),
    acceptNewPaymentChangeRequest: () => Promise.resolve({}),
    rejectNewPaymentChangeRequest: () => Promise.resolve({}),
    acceptSubscriptionChangeRequest: () => Promise.resolve({}),
    rejectSubscriptionChangeRequest: () => Promise.resolve({}),
    getNewPaymentChangeRequests: () => Promise.resolve({}),
    getNewPaymentChangeRequestBySearchText: () => Promise.resolve({}),
    addNewPaymentChangeRequest: () => Promise.resolve({}),
    addNewReturn: () => Promise.resolve({}),
    sendElasticLog: () => Promise.resolve({}),
    addNewSubscriptionCancel: () => Promise.resolve({}),
    getSubscriptionCancelByReturnRequestId: () => Promise.resolve({}),
    changeType: () => Promise.resolve({}),
    addMentorSessionTask: () => Promise.resolve({}),
    editMentorSessionTaskComment: () => Promise.resolve({}),
    editMentorSessionTask: () => Promise.resolve({}),
    getMentorSessionTasks: () => Promise.resolve({}),
    getEmergingMentorSessionTaskById: () => Promise.resolve({}),
    getMentorSessionTaskStatistics: () => Promise.resolve({}),
    getReportMentorStatistics: () => Promise.resolve({}),
    assignMentorToSessionTask: () => Promise.resolve({}),
    startSessionTaskCompletion: () => Promise.resolve({}),
    researchSessionTaskCompletion: () => Promise.resolve({}),
    addMentorTaskAndCloseSession: () => Promise.resolve({}),
    changeStatusSession: () => Promise.resolve({}),
    getCurrentUserByToken: () => Promise.resolve({}),
    getNewFreezingPupilsByDay: () => Promise.resolve({}),
    getNewFreezingPupilsByMonth: () => Promise.resolve({}),
    getBlackListClients: () => Promise.resolve({}),
    addBlackListClient: () => Promise.resolve({}),
    editBlackListClient: () => Promise.resolve({}),
    deleteBlackListClient: () => Promise.resolve({}),
    getMlClosedStatistic: () => Promise.resolve({}),
    checkReturnRequestRepeating: () => Promise.resolve({}),
    getTotalNewPupilsKpi: () => Promise.resolve({}),
    AddMobileQuestionSurvey: () => Promise.resolve({}),
    getAllMobileSurveyQuestion: () => Promise.resolve({}),
    editMobileSurveyQuestion: () => Promise.resolve({}),
    deleteMobileQuestion: () => Promise.resolve({}),
    getParentFeedbacksWithFilters: () => Promise.resolve({}),
    getSurveyReport: () => Promise.resolve({}),
    getDiscontentParentsReport: () => Promise.resolve({}),
    getReturnReport: () => Promise.resolve({}),
    getSbbLeadsReport: () => Promise.resolve({}),
    getSbbNewPupilCallsReport: () => Promise.resolve({}),
    addWebLeads: () => Promise.resolve({}),
    addMobileLeads: () => Promise.resolve({}),
    getCurrentEmployeeMobileLeads: () => Promise.resolve({}),
    changeMobileLeadStatus: () => Promise.resolve({}),
    getMobileLeadPhoneNumber: () => Promise.resolve({}),
    updatePupilCashback: () => Promise.resolve({}),
    getKassa24LinkForCashback: () => Promise.resolve({}),
    getPaymentDuration: () => Promise.resolve({}),
    saveGeneralInformation: () => Promise.resolve({}),
    getGeneralInformation: () => Promise.resolve({}),
    getClientChanges: () => Promise.resolve({}),
    getDiscontents: () => Promise.resolve({}),
    getMentorSessionTasksHistory: () => Promise.resolve({}),
    getSurveyResults: () => Promise.resolve({}),
    getSalesErrors: () => Promise.resolve({}),
    getReturnsHistory: () => Promise.resolve({}),
    getPenaltyStandards: () => Promise.resolve({}),
    addPenaltyStandard: () => Promise.resolve({}),
    updatePenaltyStandard: () => Promise.resolve({}),
    addPenaltyStandardListByExcel: () => Promise.resolve({}),
    deleteStandard: () => Promise.resolve({}),
    getReport: () => Promise.resolve({}),
    onFixNewPaymentMethodType: () => Promise.resolve({}),
    getReportLike1C: () => Promise.resolve({}),
    getSalesComparisonReport: () => Promise.resolve({}),
    getTaskTemplatesGPTNew: () => Promise.resolve({}),
    updateTaskTemplatesGPTNew: () => Promise.resolve({}),
    deleteTaskTemplatesGPTNew: () => Promise.resolve({}),
    addTaskTemplateGPTNew: () => Promise.resolve({}),
    getUzbPupils: () => Promise.resolve({}),
    getFirstPlanDate: () => Promise.resolve({}),
    getClassFirstPlanDate: () => Promise.resolve({}),
    getSessionsByDateAndMlLog: () => Promise.resolve({}),
    saveMlBotResponseEvaluation: () => Promise.resolve({}),
    addB2BTeacherWeeklyPlan: () => Promise.resolve({}),
    getB2BTeacherPlan: () => Promise.resolve({}),
    getClassB2BTeacherPlan: () => Promise.resolve({}),
    getB2BTeacherClasses: () => Promise.resolve({}),
    getB2BTeacherPupils: () => Promise.resolve({}),
    getB2BInstitutionKPI: () => Promise.resolve({}),
    getCurrentUserInstitutionFirstPlan: () => Promise.resolve({}),
    getB2BTeacherKPI: () => Promise.resolve({}),
    addNewFreezingToB2BPupils: () => Promise.resolve({}),
    getMarketingFunnelStatistic: () => Promise.resolve({}),
    getMarketingContentStatistic: () => Promise.resolve({}),
    saveSalesFunnelCost: () => Promise.resolve({}),
    getMarketingCreativeStatistic: () => Promise.resolve({}),
    addMentorPenalty: () => Promise.resolve({}),
    getMentorPenaltyList: () => Promise.resolve({}),
    deleteMentorPenalty: () => Promise.resolve({}),
    distribePupilsToSBB: () => Promise.resolve({}),
    acceptProcessedPupilSbb: () => Promise.resolve({}),
    getCreatives: () => Promise.resolve({}),
    addCreative: () => Promise.resolve({}),
    getLessonVideos: () => Promise.resolve({}),
    addLessonVideo: () => Promise.resolve({}),
    editLessonVideo: () => Promise.resolve({}),
    deleteLessonVideo: () => Promise.resolve({}),
    editContentEmployeePermission: () => Promise.resolve({}),
    getLessonPresentations: () => Promise.resolve({}),
    addLessonPresentation: () => Promise.resolve({}),
    editLessonPresentation: () => Promise.resolve({}),
    approveLessonPresentation: () => Promise.resolve({}),
    addLessonPresentationVideoLink: () => Promise.resolve({}),
    getLessonPresentationHistory: () => Promise.resolve({}),
    addTaskMistake: () => Promise.resolve({}),
    getTaskMistakes: () => Promise.resolve({}),
    getTaskMistakesHistory: () => Promise.resolve({}),
    changeTaskMistakeStatus: () => Promise.resolve({}),
    changeMultipleTaskMistakeStatus: () => Promise.resolve({}),
    getTaskMistake: () => Promise.resolve({}),
    getTaskMistakeByType: () => Promise.resolve({}),
    changeTaskMistakeComment: () => Promise.resolve({}),
    addNewMathTask: () => Promise.resolve({}),
    getNewMathTasks: () => Promise.resolve({}),
    changeNewMathTask: () => Promise.resolve({}),
    sendCashbackToUzbPupil: () => Promise.resolve({}),
    sendCashbackToAzePupil: () => Promise.resolve({}),
    acceptAtmosCashback: () => Promise.resolve({}),
    getProductCrmStatistic: () => Promise.resolve({}),
    updateUntranslatedTasks: () => Promise.resolve({}),
    uploadFile: () => Promise.resolve({}),
    enterTasksDifficutlyScoreFile: () => Promise.resolve({}),
    getTasksListWithScore: () => Promise.resolve({}),
    getNotCompletedTasks: () => Promise.resolve({}),
    getMarketingReport: () => Promise.resolve({}),
    addEmployeeSuggestion: () => Promise.resolve({}),
    getCurrentEmployeeSuggestions: () => Promise.resolve({}),
    getEmployeeSuggestions: () => Promise.resolve({}),
    getEmployeeSuggestionById: () => Promise.resolve({}),
    updateEmployeeSuggestionStatus: () => Promise.resolve({}),
    addCommentToEmployeeSuggestion: () => Promise.resolve({}),
    addEmployeeSurvey: () => Promise.resolve({}),
    getEmployeeSurveys: () => Promise.resolve({}),
    getSurveyDetails: () => Promise.resolve({}),
    setActiveToSurvey: () => Promise.resolve({}),
    getEmployeeSurveysToPass: () => Promise.resolve({}),
    getSurveyQuestionsToPass: () => Promise.resolve({}),
    passEmployeeSurvey: () => Promise.resolve({}),
    shouldToPassEmployeeSurvey: () => Promise.resolve({}),
    getPassedSurveyList: () => Promise.resolve({}),
    getPassedSurveyEmployeesList: () => Promise.resolve({}),
    getPassedVoteResults: () => Promise.resolve({}),
    getEmployeeAnswersToSurvey: () => Promise.resolve({}),
    getHREmployeeNotesByEmployeeId: () => Promise.resolve({}),
    updateHREmployeeNotesByEmployeeId: () => Promise.resolve({}),
    getAllHRNoteTypes: () => Promise.resolve({}),
    geHREmployeeNotesStatistics: () => Promise.resolve({}),
    addOrEditGameItem: () => Promise.resolve({}),
    getGameItems: () => Promise.resolve({}),
    deleteGameItem: () => Promise.resolve({}),
    getCurrentEmployeeRequestedSalaryUpdateItems: () => Promise.resolve({}),
    createEmployeeSalaryUpdateRequest: () => Promise.resolve({}),
    getEmployeeSalaryItems: () => Promise.resolve({}),
    approveEmployeeSalaryUpdate: () => Promise.resolve({}),
    addEmployeeSalary: () => Promise.resolve({}),
    getSevenDaysStatistics: () => Promise.resolve({}),
    getMobileUserStatistic: () => Promise.resolve({}),
    getMobileStandardUserStatistic: () => Promise.resolve({}),
    getEmployeeRoleHistoryStatistics: () => Promise.resolve({}),
    getAllITDuties: () => Promise.resolve({}),
    getAllITDutiesByUserId: () => Promise.resolve({}),
    addItDuties: () => Promise.resolve({}),
    editITDuty: () => Promise.resolve({}),
    getLastFixedSupport: () => Promise.resolve({}),
    saveRequestMark: () => Promise.resolve({}),
    getAllSupportRequests: () => Promise.resolve({}),
    getSupportRequestsByUserId: () => Promise.resolve({}),
    getITEmployees: () => Promise.resolve({}),
    getITSupportRequestsByCurrentUserRole: () => Promise.resolve({}),
    getITSupportStatistics: () => Promise.resolve({}),
    getITSupportAllRequests: () => Promise.resolve({}),
    addSupportRequest: () => Promise.resolve({}),
    editSupportRequest: () => Promise.resolve({}),
    respondSupportRequest: () => Promise.resolve({}),
    ChangeRequestStatus: () => Promise.resolve({}),
    getConfirmationCode: () => Promise.resolve({}),
    getSipuniAudioByPhoneNumber: () => Promise.resolve({}),
    getPromocodes: () => Promise.resolve({}),
    getAllPromocodes: () => Promise.resolve({}),
    getAudioSpeechAnalytic: () => Promise.resolve({}),
    addSpeechAnalyticManually: () => Promise.resolve({}),
    getUsersManualSpeechAnalytics: () => Promise.resolve({}),
    updateStatusManualSpeechAnalytic: () => Promise.resolve({}),
    deleteSpeechAnalytic: () => Promise.resolve({}),
    updateSpeechAnalyticEvaluation: () => Promise.resolve({}),
    searchPupilByPhoneNumber: () => Promise.resolve({}),
    addPromocode: () => Promise.resolve({}),
    getEmployeeSipuniLastCall: () => Promise.resolve({}),
    getAppsflyerLeads: () => Promise.resolve({}),
    confirmRelative: () => Promise.resolve({}),
    updateRelativeSubscriptionRequestStatus: () => Promise.resolve({}),
    getManagersQueue: () => Promise.resolve({}),
    getColdManagersQueue: () => Promise.resolve({}),
    getPupilCashbackInfo: () => Promise.resolve({}),
    getHunterWhatsappAccounts: () => Promise.resolve({}),
    addHunterWhatsappAccount: () => Promise.resolve({}),
    editHunterWhatsappAccount: () => Promise.resolve({}),
    changeHunterAccountStatus: () => Promise.resolve({}),
    sendTemplateToLeadByHunter: () => Promise.resolve({}),
    sendDistributedMailingToLeadsByHunters: () => Promise.resolve({}),
    sendDistributedMailingToLeadsByHuntersFromDb: () => Promise.resolve({}),
    getHunterSentTemplates: () => Promise.resolve({}),
    extractFromExcel: () => Promise.resolve({}),
    sendTemplateToLeads: () => Promise.resolve({}),
    getUntSubscriptionsCount: () => Promise.resolve({}),
    saveLeadsDistributions: () => Promise.resolve({}),
    saveColdLeadDistributions: () => Promise.resolve({}),
    getTodayLeadDistributions: () => Promise.resolve({}),
    getHunterLeadsStatusStatistic: () => Promise.resolve({}),
    getHunterLeadsSalesStatistic: () => Promise.resolve({}),
    onFixSubscriptionDate: () => Promise.resolve({}),
    setPupilActiveTask: () => Promise.resolve({}),
    clearManagersQueue: () => Promise.resolve({}),
    createKaspiPaymentRequest: () => Promise.resolve({}),
    createUnitedPaymentRequest: () => Promise.resolve({}),
    saveHuntersQueue: () => Promise.resolve({}),
    getHuntersFromQueue: () => Promise.resolve({}),
    getCsvSubscriptions: () => Promise.resolve({}),
    getSubscriptionsMobileStatistics: () => Promise.resolve({}),
    updateEmployeePenaltyReason: () => Promise.resolve({}),
    updateMentorPenaltyReason: () => Promise.resolve({}),
    getAutocallAudiosOfThatDay: () => Promise.resolve({}),
    callByAutocall: () => Promise.resolve({}),
    deleteAutocallRequests: () => Promise.resolve({}),
    getAutocallAccountBalance: () => Promise.resolve({}),
    getAutocallHistory: () => Promise.resolve({}),
    addManualAutocallRequest: () => Promise.resolve({}),
    addB2BManualAutocallRequest: () => Promise.resolve({}),
    getClosestAutocall: () => Promise.resolve({}),
    getAutocallBlockClients: () => Promise.resolve({}),
    addAutocallBlockClient: () => Promise.resolve({}),
    deleteAutocallBlockClient: () => Promise.resolve({}),
    getConsecutiveUnexecutedPupilsStatistic: () => Promise.resolve({}),
    getAutocallSchedules: () => Promise.resolve({}),
    updateAutocallSchedule: () => Promise.resolve({}),
    toggleAutocallScheduleActive: () => Promise.resolve({}),
    insertAutocallSchedule: () => Promise.resolve({}),
    updatePupilsParentPhoneNumber: () => Promise.resolve({}),
    updateSubscriptionsCalledStatus: () => Promise.resolve({}),
    getIncompleteTasksUsers: () => Promise.resolve({}),
    sendPushToIncompleteTasksUsers: () => Promise.resolve({}),
    validateNotificationExcel: () => Promise.resolve({}),
    sendPushToMobile: () => Promise.resolve({}),
    saveLeadsByExcel: () => Promise.resolve({}),
    importFromAmocrmExcel: () => Promise.resolve({}),
    importFromWebinarExcel: () => Promise.resolve({}),
    sendNotAttendedWebinarList: () => Promise.resolve({}),
    getNotificationTemplates: () => Promise.resolve({}),
    getNotificationsHistory: () => Promise.resolve({}),
    createNotificationTemplate: () => Promise.resolve({}),
    updateNotificationTemplate: () => Promise.resolve({}),
    deleteNotificationTemplateById: () => Promise.resolve({}),
    getAllGamificationBlocks: () => Promise.resolve({}),
    updateGamificationBlock: () => Promise.resolve({}),
    addGamificationBlock: () => Promise.resolve({}),
    addPupilGamificationSetting: () => Promise.resolve({}),
    getPupilGamificationSetting: () => Promise.resolve({}),
    getSelectedCharacterTextLines: () => Promise.resolve({}),
    clearUserLastPurchases: () => Promise.resolve({}),
    getMobileSurveys: () => Promise.resolve({}),
    addMobileSurvey: () => Promise.resolve({}),
    editMobileSurvey: () => Promise.resolve({}),
    getUserResponse: () => Promise.resolve({}),
    getMailingWhatsappTemplates: () => Promise.resolve({}),
    createMailingWhatsappTemplate: () => Promise.resolve({}),
    getMailingWhatsappTemplate: () => Promise.resolve({}),
    updateMailingWhatsappTemplate: () => Promise.resolve({}),
    deleteMailingWhatsappTemplate: () => Promise.resolve({}),
    getNonCompletingPupilsExcel: () => Promise.resolve({}),
    getWhatsappMailingReport: () => Promise.resolve({}),
  },
  global: {
    INFINITY: '∞',
    isAuthenticated: () => true,
    isAuthenticatedWithToken: () => true,
    getTokenName: () => 'token',
    getToken: () => 'mock-token',
    setUser: () => {},
    getUser: () => ({
      id: 1,
      firstname: 'John',
      surname: 'Doe',
      isTeacher: false,
      isParent: false,
      isSarafanEditor: false,
      isMobileUser: false,
      isUntTester: false,
      isLeadDivider: false,
      isScienceAcademyPupil: false,
      isSanSchoolClient: false,
      isB2BClient: false,
      isAbleToPayout: false,
      pupil: {
        language: 'russian',
        country: 'Kazakhstan' as const,
        class: { grade: 4 },
      },
    }),
    hasParent: () => false,
    getParentPhoneNumber: () => '',
    getUserId: () => 1,
    isTestUser: () => false,
    isScienceAcademyPupil: () => false,
    isPupilUser: () => true,
    isParentUser: () => false,
    isSanSchoolClient: () => false,
    isB2BClient: () => false,
    isSarafanEditor: () => false,
    isMobileUser: () => false,
    isUntTester: () => false,
    isLeadDivider: () => false,
    isFarmerLeadDivider: () => false,
    isB2CClient: () => true,
    isB2BClientAbleToPayout: () => false,
    isTeacherUser: () => false,
    getAutocallToken: () => 'mock-token',
    isQalanTeacher: () => false,
    isMarketer: () => false,
    isAdmin: () => false,
    isMainAdmin: () => false,
    isEmployee: () => false,
    isB2CEmployee: () => false,
    isManager: () => false,
    isB2BTeacher: () => false,
    isB2BAdmin: () => false,
    isContentEmployee: () => false,
    isItEmployee: () => false,
    isItDuty: () => false,
    isSuperAppAdmin: () => false,
    isReturnManager: () => false,
    isSalesDepartmentRole: () => false,
    isSbbEmployee: () => false,
    isContentEmployeeCanAddTaskMistakes: () => false,
    isContentEmployeeCanAddNewTasks: () => false,
    isContentEmployeeWithLimitedAccess: () => false,
    setLanguage: () => {},
    getLanguage: () => 'russian' as const,
    setHost: () => {},
    getHost: () => 'localhost',
    getHostNameWithHTTP: () => 'http://localhost',
    getLanguageByPupilLanguage: () => 'russian' as const,
    getAbbreviatedLanguage: () => 'ru',
    getAbbreviatedLanguageByHost: () => 'ru',
    isLanguageAzerbaijanSelected: () => false,
    isLocationLocalhost: () => true,
    isLocationQalanSchool: () => false,
    isLocationQalanKz: () => false,
    isLocationQalanRu: () => false,
    isLocationQalanUz: () => false,
    isLocationQalanAz: () => false,
    isLocationQalanEg: () => false,
    isLocationTestQalan: () => false,
    isLocationPreprodQalan: () => false,
    isPupilFromKz: () => true,
    isKazPupil: () => true,
    isSchoolPupil: () => false,
    isAzePupil: () => false,
    isEgyPupil: () => false,
    isGlobalLanguageRussian: () => true,
    getSalesCrmDomain: () => 'crm.qalan.kz',
    getFontSizeFactorName: () => 'normal',
    getFontSizeFactor: () => 1,
    isMobileBrowser: () => false,
    getCalculatorCellWidth: () => 50,
    getCalculatorCellCoefficient: () => 1,
    isAndroidBrowser: () => false,
    isIPhoneBrowser: () => false,
    isTouchDevice: () => false,
    isTouchDeviceOrMobileBrowser: () => false,
    getIosVersion: () => 0,
    translate: (text: string) => text,
    translateWithLanguage: (text: string) => text,
    translateTasks: (text: string) => text,
    translateValues: (text: string, textRus: string, textEng: string) =>
      textRus,
    translateValueFromObject: (obj: Record<string, string>, value: string) =>
      value,
    dontCloseIfBackClicked: () => {},
    saveLastAnswer: () => {},
    getLastAnswer: () => null,
    getCountryCode: () => 7,
    getCountryCodeAsLetters: () => 'KZ',
    getCurrentCurrency: () => 'KZT',
    calculateForCurrentCurrency: (money: number) => money,
    getCurrencyByDepartment: () => 'KZT' as const,
    isHREmployee: () => false,
    isCalculatorInvisible: () => false,
    isHRDirector: () => false,
    isEmployeeDeleted: () => false,
    isHRDashboardAvailable: () => false,
    isPowerBIDashboardAvailable: () => false,
    willCheckToPassSurvey: () => false,
    willCheckToPassSalesManager: () => false,
    getEmployeeCompany: () => 'qalan.kz',
    getEmployeeRole: () => 'sales_manager' as const,
    getRolesByDepartment: () => [],
    getSupportRequestStatuses: () => [],
    isEmployeeDataAnalyst: () => false,
    isB2BEmployee: () => false,
    getTeacherInstitutionId: () => 0,
    getPupilGradeForArabic: () => 4,
    getPublicOfferLink: () => 'https://qalan.kz/public-offer',
    getPrivacyPolicyLink: () => 'https://qalan.kz/privacy-policy',
    hasArabicSymbols: () => false,
    changeBodyClassByLanguage: () => {},
    getFontSizeByFontSizeFactor: (mainFontSize: number) => mainFontSize,
    getDivisionSymbol: () => '÷',
    getMultiplicationSymbol: () => '×',
    isWebView: () => false,
  },
  localize: {
    headerTitle: 'Mock Header',
    discontentReason: 'Mock Discontent Reason',
    discontentReasons: {
      serviceReason: {
        title: 'Service Reason',
        noTimelyCommunication: 'No timely communication',
        mentorRude: 'Mentor rude',
        mentorExplainsBadly: 'Mentor explains badly',
        mentorInexperienced: 'Mentor inexperienced',
        mentorMisled: 'Mentor misled',
        mentorPromisedButFailed: 'Mentor promised but failed',
      },
      managerReason: {
        title: 'Manager Reason',
        misinformation: 'Misinformation',
        overExpectations: 'Over expectations',
        managerRude: 'Manager rude',
        managerFailedToInform: 'Manager failed to inform',
        registrationError: 'Registration error',
      },
      clientReason: {
        title: 'Client Reason',
        noResult: 'No result',
        lostInterest: 'Lost interest',
        noControl: 'No control',
        noDiagnosis: 'No diagnosis',
        noFourStageLearning: 'No four stage learning',
        inadequate: 'Inadequate',
        manyPenaltyTasks: 'Many penalty tasks',
        topicMismatch: 'Topic mismatch',
        expectationReality: 'Expectation reality',
        priceValueMismatch: 'Price value mismatch',
      },
      productReason: {
        title: 'Product Reason',
        materialQuality: 'Material quality',
        unclearTasks: 'Unclear tasks',
        taskErrors: 'Task errors',
        repetitiveTasks: 'Repetitive tasks',
        olympiadUpdates: 'Olympiad updates',
        missingTopics: 'Missing topics',
      },
      appReason: {
        title: 'App Reason',
        taskBug: 'Task bug',
        appBug: 'App bug',
        serverIssues: 'Server issues',
        inconvenientInterface: 'Inconvenient interface',
        messageNotReceived: 'Message not received',
      },
      systemReason: {
        title: 'System Reason',
        spamMessages: 'Spam messages',
        autoCall: 'Auto call',
        freezing: 'Freezing',
        cashbackIssues: 'Cashback issues',
      },
    },
    selectCategory: 'Select category',
    selectReasons: 'Select reasons',
    errors: {
      missingUpperCaseLetterPassword: 'Missing upper case letter in password',
      missingNumberPassword: 'Missing number in password',
      lengthOfPasswordIsTooShort: 'Password is too short',
    },
    realDiscontentReason: 'Real discontent reason',
    nameManager: 'Manager name',
    region: 'Region',
    whoAccepted: 'Who accepted',
    penaltyStandards: 'Penalty standards',
    accept: 'Accept',
    accepting: 'Accepting',
    notAccept: 'Not accept',
    notAccepting: 'Not accepting',
    freezingDays: 'Freezing days',
    sender: 'Sender',
    newFreezingRequests: 'New freezing requests',
    requestForFreezing: 'Request for freezing',
    comment: 'Comment',
    whoSent: 'Who sent',
    causeCount: 'Cause count',
    showMore: 'Show more',
    errorOutputCheck: 'Error output check',
    errorParentNotFound: 'Parent not found',
    bankAcc: 'Bank account',
    new: 'New',
    percent: 'Percent',
    freezingCount: 'Freezing count',
    completedCount: 'Completed count',
    NotCompletedCount: 'Not completed count',
    accepted: 'Accepted',
    notAccepted: 'Not accepted',
    repeatedRequest: 'Repeated request',
    makeReturn: 'Make return',
    network: 'Network',
    fullAmount: 'Full amount',
    kaspiCheckLink: 'Kaspi check link',
    title: 'Title',
    educationCenter: 'Education center',
    saved: 'Saved',
    writeRequestReason: 'Write request reason',
    stepNumber: 'Step number',
    inTesting: 'In testing',
    theory: 'Theory',
    enterLastAnswer: 'Enter last answer',
    chooseLanguage: 'Choose language',
    useAnotherBrowserWebView: 'Use another browser for WebView',
    timezoneWarning: 'Timezone warning',
    pricing: 'Pricing',
    diagnostics: 'Diagnostics',
    untDiagnostics: 'UNT diagnostics',
    passDiagnostics: 'Pass diagnostics',
    onlyNewStudents: 'Only new students',
    subscriptionHistory: 'Subscription history',
    hasSubscription: 'Has subscription',
    hasMobileApp: 'Has mobile app',
    noMobileApp: 'No mobile app',
    researcher: 'Researcher',
    afterCommisionSum: 'After commission sum',
    returnCommission: 'Return commission',
    afterSumCommision: 'After sum commission',
    commission: 'Commission',
    fileSum: 'File sum',
    oneCSum: '1C sum',
    platform: 'Platform',
    differences: 'Differences',
    insertFile: 'Insert file',
    listTasks: 'List tasks',
    insertExelFile: 'Insert Excel file',
    checkAnomaly: 'Check anomaly',
    superBonus: 'Super bonus',
    targetReport: 'Target report',
    marketingReport: 'Marketing report',
    businessCard: 'Business card',
    freedomBankStatement: 'Freedom bank statement',
    tengeDifferences: 'Tenge differences',
    valutDifferences: 'Valut differences',
    extractDay: 'Extract day',
    reportDay: 'Report day',
    isRealtimeConnectedToMessages: 'Is realtime connected to messages',
    isItConnectedToRealtimeTasks: 'Is it connected to realtime tasks',
    showOnlyNonAnsweredMessages: 'Show only non answered messages',
    insertingAfterLoading: 'Inserting after loading',
    searchInDatabaseByNumber: 'Search in database by number',
    searcher: 'Searcher',
    loader: 'Loader',
    twoTimeMail: 'Two time mail',
    sixTimeMail: 'Six time mail',
    howManySend: 'How many send',
    howManySended: 'How many sended',
    whenStart: 'When start',
    whenEnd: 'When end',
    readed: 'Readed',
    personalStudy: 'Personal study',
    generalMath: 'General math',
    UNT: 'UNT',
    mathLiteracy: 'Math literacy',
    mathLiteracyShort: 'Math literacy short',
    topicsLearn: 'Topics learn',
    payments: 'Payments',
    prepayments: 'Prepayments',
    awards: 'Awards',
    subscriptionRequest: 'Subscription request',
    farmerCrm: 'Farmer CRM',
    myFinishedPersonalStudies: 'My finished personal studies',
    subscribedLearners: 'Subscribed learners',
    questions: 'Questions',
    answers: 'Answers',
    answer: 'Answer',
    answerOptions: 'Answer options',
    notRegisteredInMessenger: 'Not registered in messenger',
    blockedUs: 'Blocked us',
    QCD: 'QCD',
    learning: 'Learning',
    learningResults: 'Learning results',
    executionTime: 'Execution time',
    contactedThreeTimes: 'Contacted three times',
    numberOfParents: 'Number of parents',
    employeeStatistics: 'Employee statistics',
    statisticsOnIssues: 'Statistics on issues',
    whatDayFrom: 'What day from',
    whatDayTo: 'What day to',
    tenge: 'Tenge',
    howManyDaysQuestion: 'How many days question',
    uploadQuestions: 'Upload questions',
    selectQuestion: 'Select question',
    sbbReturnRequest: {
      assignedSbbEmployee: 'Assigned SBB employee',
      callTime: 'Call time',
      createReturn: 'Create return',
      inProcess: 'In process',
      infoFromSBB: 'Info from SBB',
      chat: 'Chat',
      sipuni: 'Sipuni',
      whatsapp: 'Whatsapp',
      call: 'Call',
      uploadScreen: 'Upload screen',
      uploadAudio: 'Upload audio',
      linkToCall: 'Link to call',
      claim: 'Claim',
      infoAboutPupil: 'Info about pupil',
      infoForReturnManager: 'Info for return manager',
      count: 'Count',
      new: 'New',
      tnbOrInProcess: 'TNB or in process',
      solved: 'Solved',
      notSolved: 'Not solved',
      returnCreated: 'Return created',
      confirmationType: 'Confirmation type',
      createdFromSbb: 'Created from SBB',
      tnb: 'TNB',
      deleted: 'Deleted',
    },
    whoseStatistics: 'Whose statistics',
    personalStudyDeleteOrStudentFinished:
      'Personal study delete or student finished',
    olympiadPreview: {
      letsYourChildOne: 'Lets your child one',
      letsYourChildTwo: 'Lets your child two',
      letsYourChildThree: 'Lets your child three',
      letsGiveChild: 'Lets give child',
      joinOlympiad: 'Join olympiad',
      aboutOlympiad: 'About olympiad',
      aroundClass: 'Around class',
      aroundClassText: 'Around class text',
      threeOnline: 'Three online',
      threeOnlineTextOne: 'Three online text one',
      threeOnlineTextTwo: 'Three online text two',
      fondHundred: 'Fond hundred',
      fondHundredText: 'Fond hundred text',
      fourTourFree: 'Four tour free',
      fourTourFreeTextOne: 'Four tour free text one',
      fourTourFreeTextTwo: 'Four tour free text two',
      prizeOlympiad: 'Prize olympiad',
      prizeOlympiadFirst: 'Prize olympiad first',
      prizeOlympiadSecond: 'Prize olympiad second',
      prizeOlympiadThird: 'Prize olympiad third',
      afterWinner: 'After winner',
      secondClass: 'Second class',
      grandWinner: 'Grand winner',
      checkList: 'Check list',
      howJoin: 'How join',
      joinOne: 'Join one',
      joinTwo: 'Join two',
      joinThree: 'Join three',
      joinFour: 'Join four',
      whatQalan: 'What Qalan',
      yourLevel: 'Your level',
      yourLevelText: 'Your level text',
      diagnostic: 'Diagnostic',
      diagnosticText: 'Diagnostic text',
      personalStudy: 'Personal study',
      personalStudyText: 'Personal study text',
      videoStudy: 'Video study',
      videoStudyText: 'Video study text',
      mentorSupport: 'Mentor support',
      mentorSupportText: 'Mentor support text',
      mentorCall: 'Mentor call',
      mentorCallText: 'Mentor call text',
      cashbackSum: 'Cashback sum',
      cashbackSumText: 'Cashback sum text',
      dailyTask: 'Daily task',
      dailyTaskText: 'Daily task text',
      cashback: 'Cashback',
      cashbackText: 'Cashback text',
      faq: 'FAQ',
      whyFiveClass: 'Why five class',
      watchingVideo: 'Watching video',
      freeOlympiad: 'Free olympiad',
      olympiadFree: 'Olympiad free',
      olympiadFreeText: 'Olympiad free text',
      olympiadTime: 'Olympiad time',
      olympiadTimeTextOne: 'Olympiad time text one',
      olympiadTimeTextTwo: 'Olympiad time text two',
      olympiadTimeTextThree: 'Olympiad time text three',
      olympiadTimeTextFour: 'Olympiad time text four',
      secondTry: 'Second try',
      secondTryText: 'Second try text',
      oldMember: 'Old member',
      oldMemberText: 'Old member text',
      onlyThree: 'Only three',
      onlyThreeText: 'Only three text',
      aiQalan: 'AI Qalan',
    },
    calculatorList: {
      fraction: 'Fraction',
      plus: 'Plus',
      multiply: 'Multiply',
      power: 'Power',
      minus: 'Minus',
      divide: 'Divide',
      comma: 'Comma',
      sqrt: 'Square root',
      removeLastChar: 'Remove last char',
      semicolon: 'Semicolon',
      point: 'Point',
      functions: 'Functions',
      pi: 'Pi',
      angle: 'Angle',
      degree: 'Degree',
      emptySystem: 'Empty system',
      factorial: 'Factorial',
      emptyCell: 'Empty cell',
      limit: 'Limit',
      infinity: 'Infinity',
    },
    tasks: 'Tasks',
    createArequest: 'Create a request',
    typesOfSessionSasks: {
      notHappy: 'Not happy',
      return: 'Return',
      calculationExplanation: 'Calculation explanation',
      givingAdvice: 'Giving advice',
    },
    discontentParents: {
      status: 'Status',
      sentForAssessmentSbb: 'Sent for assessment SBB',
      verifiedBySbb: 'Verified by SBB',
      checkerSbb: 'Checker SBB',
      chooseSbb: 'Choose SBB',
      sbbEmployee: 'SBB employee',
      isSolved: 'Is solved',
      isAccepted: 'Is accepted',
      viewed: 'Viewed',
      critery: 'Critery',
      open: 'Open',
      aboutTheClient: 'About the client',
      evaluate: 'Evaluate',
      commentSbb: 'Comment SBB',
      controlDiscontents: 'Control discontents',
      dataFromMentor: 'Data from mentor',
    },
    sourcesOfSessionTasks: {
      chat: 'Chat',
      call: 'Call',
      truant: 'Truant',
      sbb: 'SBB',
      marketing: 'Marketing',
      opHunters: 'OP hunters',
      headHolder: 'Head holder',
      discontent: 'Discontent',
      discontentSbb: 'Discontent SBB',
      discontentRepeatedSbb: 'Discontent repeated SBB',
    },
    ConsultingSubcategories: {
      techProblems: 'Tech problems',
      script: 'Script',
      motivation: 'Motivation',
      other: 'Other',
    },
    ConsultingSubcategory: 'Consulting subcategory',
    source: 'Source',
    sessionTaskTable: {
      whoSent: 'Who sent',
      designatedMentor: 'Designated mentor',
      taskType: 'Task type',
      timeOfInsertion: 'Time of insertion',
      reasonForReturn: 'Reason for return',
      communicationTime: 'Communication time',
      status: 'Status',
      comment: 'Comment',
      isTaskTaken: 'Is task taken',
      taskTakenAt: 'Task taken at',
    },
    farmerLeadStatus: {
      sold: 'Sold',
      notSold: 'Not sold',
      thinking: 'Thinking',
      prepayment: 'Prepayment',
      tnb: 'TNB',
    },
    taskMistakeStatus: {
      mistake: 'Mistake',
      codeReview: 'Code review',
      inProcess: 'In process',
      review: 'Review',
      fixed: 'Fixed',
    },
    taskMistakeInfo: {
      server: 'Server',
      language: 'Language',
      author: 'Author',
      createdAt: 'Created at',
      lastEditedBy: 'Last edited by',
      lastUpdatedAt: 'Last updated at',
      filterByLastUpdatedEmployee: 'Filter by last updated employee',
    },
    taskMistakeTypes: {
      howToFix: 'How to fix',
      causedBy: 'Caused by',
      isPersonalStudyTaskMistake: 'Is personal study task mistake',
      selectMistakeTypes: 'Select mistake types',
      spelling: 'Spelling',
      description: 'Description',
      answer: 'Answer',
      solution: 'Solution',
      svg: 'SVG',
      generation: 'Generation',
    },
    departmentTypes: {
      sales: 'Sales',
      service: 'Service',
      HR: 'HR',
      finance: 'Finance',
      content: 'Content',
      SBB: 'SBB',
      marketing: 'Marketing',
    },
    reportModal: {
      taskCount: 'Task count',
      reportTaskCount: 'Report task count',
      diagnostic: 'Diagnostic',
      allTime: 'All time',
      averageTaskTime: 'Average task time',
      personalTaskLesson: 'Personal task lesson',
    },
    mainPage: {
      pTech: 'P Tech',
      binom: 'Binom',
      zaman: 'Zaman',
      ork: 'Ork',
      zhanAu: 'Zhan Au',
      sUalikhan: 'S Ualikhan',
      urk: 'Urk',
      snm: 'SNM',
      jos: 'Jos',
      alm: 'Alm',
      dailyUsers: 'Daily users',
      countUsers: 'Count users',
      countPupils: 'Count pupils',
      taskLevel: 'Task level',
      paidCashback: 'Paid cashback',
      timerMentors: 'Timer mentors',
      register: 'Register',
      consultation: 'Consultation',
      olympiad: 'Olympiad',
      mainTitle: 'Main title',
      mainText: 'Main text',
      olympiadText: 'Olympiad text',
      qalanIs: 'Qalan is',
      appForPupil: 'App for pupil',
      appForPupilText: 'App for pupil text',
      appForParent: 'App for parent',
      appForParentText: 'App for parent text',
      supportMentor: 'Support mentor',
      supportMentorText: 'Support mentor text',
      lotOfVideo: 'Lot of video',
      lotOfVideoText: 'Lot of video text',
      factText: 'Fact text',
      afterStudy: 'After study',
      afterStudyText: 'After study text',
      suspendPupil: 'Suspend pupil',
      progressViewParent: 'Progress view parent',
      monitorPupil: 'Monitor pupil',
      messageForParent: 'Message for parent',
      trueEducation: 'True education',
      guardian: 'Guardian',
      takeConsultation: 'Take consultation',
      takeConsultationText: 'Take consultation text',
      agreement: 'Agreement',
      howWorkApp: 'How work app',
      forB2B: 'For B2B',
      forB2BFirstText: 'For B2B first text',
      forB2BSecondText: 'For B2B second text',
      forB2BThirdText: 'For B2B third text',
      forB2BFourthText: 'For B2B fourth text',
      ourClient: 'Our client',
      zamanSchool: 'Zaman school',
      phizTech: 'Phiz tech',
      josSchool: 'Jos school',
      ourProductQalan: 'Our product Qalan',
      oferta: 'Oferta',
      confidentialInformation: 'Confidential information',
      ourProduct: 'Our product',
      contacts: 'Contacts',
      salesContacts: 'Sales contacts',
      moreQuestions: 'More questions',
      mentorContacts: 'Mentor contacts',
      workTimes: 'Work times',
      freeDiagnostics: 'Free diagnostics',
      dontLoveButCanWork: 'Dont love but can work',
      goodClientNotWantToStudy: 'Good client not want to study',
      employeeSolvedProblem: 'Employee solved problem',
      quantity: 'Quantity',
      employees: 'Employees',
      employeesStat: 'Employees stat',
      stat: 'Stat',
      variantQuant: 'Variant quant',
      employeeName: 'Employee name',
      notEnded: 'Not ended',
      tnb: 'TNB',
      ended: 'Ended',
      divided: 'Divided',
      canNotMark: 'Can not mark',
    },
    sbbReturnCause: {
      category: 'Category',
      mean: 'Mean',
      closedByWho: 'Closed by who',
      returnMonth: 'Return month',
      part: 'Part',
      sum: 'Sum',
    },
    sbbSurvey: {
      answerVariant: 'Answer variant',
    },
    nextPupil: 'Next pupil',
    taskExp: {
      openTaskExp: 'Open task exp',
      closeTaskExp: 'Close task exp',
      allTaskExp: 'All task exp',
      explainedCount: 'Explained count',
      notExplainedCount: 'Not explained count',
      justClosedCount: 'Just closed count',
      reassignedTaskExp: 'Reassigned task exp',
      explainedPercentage: 'Explained percentage',
      notExplainedPercentage: 'Not explained percentage',
      tnbPercentage: 'TNB percentage',
      notContactPercentage: 'Not contact percentage',
      mentorResponseTime: 'Mentor response time',
      fullExpTime: 'Full exp time',
      explainTime: 'Explain time',
      explain: 'Explain',
      taskOpenTime: 'Task open time',
      taskExplainedTime: 'Task explained time',
      taskExpDuration: 'Task exp duration',
    },
    callLater: 'Call later',
    sessionList: {
      firstResponse: 'First response',
      minute: 'Minute',
      seconds: 'Seconds',
      allAverageResponseTime: 'All average response time',
      allMentorResponseTime: 'All mentor response time',
      allMLCloseTime: 'All ML close time',
      allMentorSessionCloseTimeFromTaking:
        'All mentor session close time from taking',
      allMentorSessionCloseTimeFromReceipt:
        'All mentor session close time from receipt',
      allSessionCloseTimeFromTaking: 'All session close time from taking',
      allSessionCloseTimeFromReceipt: 'All session close time from receipt',
      allSessionCloseTime: 'All session close time',
      median: 'Median',
      openSession: 'Open session',
      closeSession: 'Close session',
      allClosedSessions: 'All closed sessions',
      sessionsClosedByMentor: 'Sessions closed by mentor',
      sessionsClosedByBot: 'Sessions closed by bot',
      sessionAverageCloseFromTaking: 'Session average close from taking',
      sessionAverageCloseFromReceipt: 'Session average close from receipt',
      firstResponseRemoveOpenedAt: 'First response remove opened at',
      allSessions: 'All sessions',
      markedSession: 'Marked session',
      notMarkedSession: 'Not marked session',
      justClosed: 'Just closed',
      reassigned: 'Reassigned',
      solved: 'Solved',
      notSolved: 'Not solved',
      mentorAverageResponse: 'Mentor average response',
      sessionAverageClose: 'Session average close',
      session: 'Session',
      sessionOpenTime: 'Session open time',
      sessionCloseTime: 'Session close time',
      sessionDuration: 'Session duration',
      mark: 'Mark',
      solvedStatus: 'Solved status',
      notMarked: 'Not marked',
      simplyClosed: 'Simply closed',
      endedTime: 'Ended time',
    },
    adjustingTooltips: 'Adjusting tooltips',
    taskDifficulty: 'Task difficulty',
    taskNumbers: 'Task numbers',
    classProgressPercentage: 'Class progress percentage',
    standardKPI: 'Standard KPI',
    schoolProgressPercentage: 'School progress percentage',
    averageTaskCompletionTime: 'Average task completion time',
    averageSchoolTaskCompletionTime: 'Average school task completion time',
    selectMinimumOfNumbersOfBatteries: 'Select minimum of numbers of batteries',
    beginningOfTheWeek: 'Beginning of the week',
    numberOfBatteries: 'Number of batteries',
    viewStudent: 'View student',
    numberOfCompletedBatteries: 'Number of completed batteries',
    averageTimeSpentCompleteBattery: 'Average time spent complete battery',
    numberOfLeftBatteries: 'Number of left batteries',
    studentPerformance: 'Student performance',
    studentsPerformance: 'Students performance',
    telegramChatList: {
      telegramChat: 'Telegram chat',
      letters: 'Letters',
      statistics: 'Statistics',
    },
    chooseDate: 'Choose date',
    sessionTaskStatisticsList: {
      refund: 'Refund',
      dissatisfied: 'Dissatisfied',
      consulting: 'Consulting',
      taskExplain: 'Task explain',
      hasSubscription: 'Has subscription',
      openSession: 'Open session',
      resolved: 'Resolved',
      undecided: 'Undecided',
    },
    totalMentorKpiList: {
      studentNumbers: 'Student numbers',
      performersNumbers: 'Performers numbers',
      perfomanceKPI: 'Performance KPI',
      explanationKPI: 'Explanation KPI',
      processingKPI: 'Processing KPI',
      freezing: 'Freezing',
      newStudents: 'New students',
      allStudents: 'All students',
    },
    content: 'Content',
    salesTime: 'Sales time',
    marketing: 'Marketing',
    taskMistakeStatuses: {
      new: 'New',
      codeInReview: 'Code in review',
      inReview: 'In review',
      review: 'Review',
      fixed: 'Fixed',
      notFixed: 'Not fixed',
      notFinished: 'Not finished',
    },
    lastModifiedBy: 'Last modified by',
    DashboardSections: {
      functionals: 'Functionals',
      statistics: 'Statistics',
      telegramMessage: 'Telegram message',
      sessions: 'Sessions',
      records: 'Records',
    },
    employeeTestTitles: {
      temperamentTest: 'Temperament test',
      personalityTest: 'Personality test',
    },
    current: 'Current',
    byInterval: 'By interval',
    mobileUserStatistics: 'Mobile user statistics',
    hrDashboard: {
      recommendation: 'Recommendation',
      complaint: 'Complaint',
      myRecommendations: 'My recommendations',
      myComplaints: 'My complaints',
      addRecommendation: 'Add recommendation',
      addComplaint: 'Add complaint',
      yourRecommendation: 'Your recommendation',
      yourComplaint: 'Your complaint',
      recommendations: 'Recommendations',
      complaints: 'Complaints',
      surveys: 'Surveys',
      survey: 'Survey',
      vote: 'Vote',
      createSurvey: 'Create survey',
      createVote: 'Create vote',
      noteAboutEmployee: 'Note about employee',
      noteStatistics: 'Note statistics',
      surveyStatistics: 'Survey statistics',
      details: 'Details',
      allRecommendations: 'All recommendations',
      allComplaints: 'All complaints',
      needToPass: 'Need to pass',
      passed: 'Passed',
      passing: 'Passing',
      passSurvey: 'Pass survey',
      passVote: 'Pass vote',
      insertYourAnswer: 'Insert your answer',
      leaveComments: 'Leave comments',
    },
    scaleQuestionTypeAnswers: {
      veryBad: 'Very bad',
      bad: 'Bad',
      neutral: 'Neutral',
      good: 'Good',
      veryGood: 'Very good',
    },
    promocode: 'Promocode',
    funnelConversion: 'Funnel conversion',
    contentMarketingConversion: 'Content marketing conversion',
    personalStudyHasNotBeenStarted: 'Personal study has not been started',
    showAudioChat: 'Show audio chat',
    isActive: 'Is active',
    showAdditionalInfromation: 'Show additional information',
    clearAudioLinks: 'Clear audio links',
    translationError: 'Translation error',
    kpiForThreeDays: 'KPI for three days',
    appWithPupilCount: 'App with pupil count',
    appWithParentCount: 'App with parent count',
    freezeCount: 'Freeze count',
    mentorSetCount: 'Mentor set count',
    pupilSetCount: 'Pupil set count',
    finishedQuantity: 'Finished quantity',
    nonFinishedQuantity: 'Non finished quantity',
    toggleVisibilityAudio: 'Toggle visibility audio',
    analysisAccepted: 'Analysis accepted',
    analysisNotAccepted: 'Analysis not accepted',
    studyEndDate: 'Study end date',
    leadsNotStartedPS: 'Leads not started PS',
    employeeInfo: 'Employee info',
    relativeConfirmed: 'Relative confirmed',
    RelativeSubscriptionRequestStatus: {
      new: 'New',
      accepted: 'Accepted',
      rejected: 'Rejected',
    },
    actions: 'Actions',
    sortByStatus: 'Sort by status',
    sortByEmployee: 'Sort by employee',
    chooseDepartment: 'Choose department',
    chooseEmployee: 'Choose employee',
    confirm: 'Confirm',
    relativeRelation: 'Relative relation',
    proofOfRelative: 'Proof of relative',
    chooseVariant: 'Choose variant',
    downloadBirthCertificate: 'Download birth certificate',
    downloadMarriageCertificate: 'Download marriage certificate',
    surnamesNotMatch: 'Surnames not match',
    RelativeType: {
      brother: 'Brother',
      sister: 'Sister',
      daughter: 'Daughter',
      son: 'Son',
    },
    reductionPeriod: 'Reduction period',
    englishCourse: 'English course',
    forbiddenMessage: 'Forbidden message',
    short_amount: 'Short amount',
    allCourses: 'All courses',
    relativeSubscriptionRequestStatusWasChanged:
      'Relative subscription request status was changed',
    refundCharacters: 'Refund characters',
    parentsInactiveMoreThan30: 'Parents inactive more than 30',
    untDiagnosticsLessons: 'UNT diagnostics lessons',
    sentLink: 'Sent link',
    linkSentSuccessfully: 'Link sent successfully',
    linkNotSent: 'Link not sent',
    linkGenerationInProgress: 'Link generation in progress',
    tryAfter: 'Try after',
    withoutMentor: 'Without mentor',
    informingAboutRules: {
      familiarWithInformation: 'Familiar with information',
      readRules: 'Read rules',
      ruleAboutGetCashback: 'Rule about get cashback',
    },
    termsAndConditions: {
      agreementWithTheTermsOfUse: 'Agreement with the terms of use',
      byContinuingToUseTheSite: 'By continuing to use the site',
      publicOffer: 'Public offer',
      privacyPolicy: 'Privacy policy',
      consentToTheProcessingOfPersonalData:
        'Consent to the processing of personal data',
      agreementWithThePublicOffer: 'Agreement with the public offer',
      acceptAndContinue: 'Accept and continue',
      acceptingAndContinuing: 'Accepting and continuing',
    },
    autocall: {
      instant: 'Instant',
      scheduled: 'Scheduled',
      cancelled: 'Cancelled',
      adminPanel: 'Admin panel',
      closedAutocall: 'Closed autocall',
      settings: 'Settings',
      callNow: 'Call now',
      date: 'Date',
      target: 'Target',
      chooseDays: 'Choose days',
      call: 'Call',
      history: 'History',
      ChooseDay: 'Choose day',
      audioFor: 'Audio for',
      balance: 'Balance',
      areYouSure: 'Are you sure',
      call2: 'Call',
      pupil: 'Pupil',
      parent: 'Parent',
      day: 'Day',
      time: 'Time',
      days: 'Days',
      completed: 'Completed',
      pending: 'Pending',
      b2b: 'B2B',
      chooseInstitutions: 'Choose institutions',
    },
    progressBar: {
      progress: 'Progress',
      leftUntilNextRank: 'Left until next rank',
      ranks: 'Ranks',
      youGetNewRank: 'You get new rank',
      numberTasksTraining: 'Number tasks training',
      achievements: {
        awakened: 'Awakened',
        student: 'Student',
        researcher: 'Researcher',
        practitioner: 'Practitioner',
        advanced: 'Advanced',
        master: 'Master',
        strategist: 'Strategist',
        pro: 'Pro',
        finalist: 'Finalist',
        legend: 'Legend',
        descriptions: {
          awakened: 'Awakened description',
          student: 'Student description',
          researcher: 'Researcher description',
          practitioner: 'Practitioner description',
          advanced: 'Advanced description',
          master: 'Master description',
          strategist: 'Strategist description',
          pro: 'Pro description',
          finalist: 'Finalist description',
          legend: 'Legend description',
        },
      },
    },
    salesBonus: {
      bonuses: 'Bonuses',
      shiftTurnover: 'Shift turnover',
      teamTurnover: 'Team turnover',
      dayShiftTurnover: 'Day shift turnover',
      eveningShiftTurnover: 'Evening shift turnover',
      coefficient: 'Coefficient',
      formula: 'Formula',
      shift: 'Shift',
      dayShift: 'Day shift',
      eveningShift: 'Evening shift',
      group: 'Group',
      headOfGroup: 'Head of group',
      teamLead: 'Team lead',
      trainer: 'Trainer',
      dayTrainer: 'Day trainer',
      eveningTrainer: 'Evening trainer',
      shiftTrainers: 'Shift trainers',
      groupModalHeader: 'Group modal header',
      groupModalHeader2: 'Group modal header 2',
      rubToKzt: 'Rub to KZT',
      name: 'Name',
      unknown: 'Unknown',
    },
    speechAnalytic: {
      callAnswerTime: 'Call answer time',
      searchByLink: 'Search by link',
      areYouSureToDelete: 'Are you sure to delete',
      check: 'Check',
      audioLink: 'Audio link',
      update: 'Update',
      view: 'View',
      audioChat: 'Audio chat',
      shortDescription: 'Short description',
      grade: 'Grade',
      yourGrade: 'Your grade',
      criterias: {
        kaz: {
          1: 'Kaz 1',
          2: 'Kaz 2',
          3: 'Kaz 3',
          4: 'Kaz 4',
          5: 'Kaz 5',
          6: 'Kaz 6',
          7: 'Kaz 7',
          8: 'Kaz 8',
          9: 'Kaz 9',
        },
        rus: {
          1: 'Rus 1',
          2: 'Rus 2',
          3: 'Rus 3',
          4: 'Rus 4',
          5: 'Rus 5',
          6: 'Rus 6',
        },
      },
      item: 'Item',
      expertComment: 'Expert comment',
      noComment: 'No comment',
      yourComment: 'Your comment',
      yourText: 'Your text',
      expertRecommendations: 'Expert recommendations',
      recommendations: 'Recommendations',
      insertedAt: 'Inserted at',
      updatedAt: 'Updated at',
      linkAlreadyExists: 'Link already exists',
      author: 'Author',
      linkCopied: 'Link copied',
      copyFailed: 'Copy failed',
      addAnotherAudioLink: 'Add another audio link',
      removeAudioLink: 'Remove audio link',
      maxLinksReached: 'Max links reached',
      invalidLinks: 'Invalid links',
    },
    taskExplanationStarted: 'Task explanation started',
    lastTask: 'Last task',
    research: 'Research',
    managerStatisticTable: {
      managerName: 'Manager name',
      returnSum: 'Return sum',
      returnCount: 'Return count',
      beforeFifteenDays: 'Before fifteen days',
      betweenFiftenAndThirtyDays: 'Between fifteen and thirty days',
      returnPercentOfSales: 'Return percent of sales',
    },
    powerBI: {
      generalInformation: 'General information',
      sales: 'Sales',
      fiveDayProgrev: 'Five day progrev',
      newPupilCallAnalysis: 'New pupil call analysis',
      customerService: 'Customer service',
      returnRequests: 'Return requests',
      careService: 'Care service',
      clientFeedback: 'Client feedback',
      managers: 'Managers',
      managerPenalties: 'Manager penalties',
      pupils: 'Pupils',
      pupilsAndCompletedTasks: 'Pupils and completed tasks',
      pupilsWithoutTheMobileApp: 'Pupils without the mobile app',
      pupilFreezingOverview: 'Pupil freezing overview',
      courses: 'Courses',
      qalanEnglishMonitoring: 'Qalan English monitoring',
      analytics: 'Analytics',
      coinsAndCashbackAnalytics: 'Coins and cashback analytics',
      allSessionAnalytics: 'All session analytics',
      crmAnalytics: 'CRM analytics',
    },
    whatsappTemplates: {
      extractingDataFromFile: 'Extracting data from file',
      title: 'Title',
      whatsappTemplate: 'Whatsapp template',
      loadingTemplates: 'Loading templates',
      selectTemplate: 'Select template',
      totalTemplates: 'Total templates',
      sendTemplate: 'Send template',
      createTemplate: 'Create template',
      editTemplate: 'Edit template',
      deleteTemplate: 'Delete template',
      searchTemplates: 'Search templates',
      allStatuses: 'All statuses',
      approved: 'Approved',
      pending: 'Pending',
      rejected: 'Rejected',
      paused: 'Paused',
      disabled: 'Disabled',
      refresh: 'Refresh',
      noTemplatesMatchFilters: 'No templates match filters',
      noTemplatesAvailable: 'No templates available',
      language: 'Language',
      createNewTemplate: 'Create new template',
      editingTemplate: 'Editing template',
      basicInformation: 'Basic information',
      templateNameCannotBeChangedAfterCreation:
        'Template name cannot be changed after creation',
      onlyLowercaseLettersNumbersAndUnderscoresAllowed:
        'Only lowercase letters numbers and underscores allowed',
      russian: 'Russian',
      kazakh: 'Kazakh',
      english: 'English',
      templateComponents: 'Template components',
      enterYourMessageTextHere: 'Enter your message text here',
      addButton: 'Add button',
      quickReply: 'Quick reply',
      callPhone: 'Call phone',
      visitWebsite: 'Visit website',
      yourPhoneNumber: 'Your phone number',
      websiteUrl: 'Website URL',
      templateNameIsRequired: 'Template name is required',
      templateBodyTextIsRequired: 'Template body text is required',
      createdSuccessfully: 'Created successfully',
      deletedSuccessfully: 'Deleted successfully',
      unableToEditTemplate: 'Unable to edit template',
      areYouSureYouWantToDeleteTemplate:
        'Are you sure you want to delete template',
      listOfRecipients: 'List of recipients',
      dateTimeToSend: 'Date time to send',
      sendNow: 'Send now',
    },
    whatsappMailingReport: {
      title: 'Title',
      noData: 'No data',
      overallStatistics: 'Overall statistics',
      totalSent: 'Total sent',
      totalSuccessful: 'Total successful',
      totalError: 'Total error',
      successRate: 'Success rate',
      totalInterestedReplies: 'Total interested replies',
      totalRejectedReplies: 'Total rejected replies',
      errorRate: 'Error rate',
      lastSentDate: 'Last sent date',
      sentCount: 'Sent count',
      selectDateRange: 'Select date range',
      fromDateIsAfterToDate: 'From date is after to date',
      dateRangeExceedsLimit: 'Date range exceeds limit',
      loadError: 'Load error',
      fromPhoneNumber: 'From phone number',
      template: 'Template',
      filters: 'Filters',
      noFilterResults: 'No filter results',
      allTemplates: 'All templates',
      allPhones: 'All phones',
      clearFilters: 'Clear filters',
    },
  },
  lodash: {} as typeof import('lodash'),
  enums: {
    HttpStatusCode: {} as any,
    UserActionResult: {} as any,
    TaskDescriptionType: {} as any,
    Language: {} as any,
    SocketCommand: {} as any,
    TaskSourceType: {} as any,
    CharacterLineTemplateNames: {} as any,
  },
  toast: {} as typeof import('react-toastify'),
  socket: {
    push: () => {},
    currentPupilRoom: () => '',
  },
  cookies: {} as typeof import('js-cookie'),
  helpers: {
    CyrillicTo: {
      default_numeral: () => '',
    },
    TaskHelper: {
      multipleTaskAnswerSeparator: '',
      isMultipleAnswerInputType: () => false,
      getAnswerInputsQuantity: () => 1,
      convertToArabicNumeral: () => '',
    },
    ArabicNumeralUtils: {
      isArabic: () => false,
      getDirection: () => '',
    },
  },
  eventEmitter: {
    emit: () => false,
    on: () => ({}),
    off: () => ({}),
  },
  alert: {
    showError: () => {},
    showSuccessMessage: () => {},
    showInfoMessage: () => {},
    showWarningMessage: () => {},
  },
}

// Mock data
const mockData = {
  activeTask: {
    id: 1,
    type: 'math',
    title: 'Sample Math Task',
    fields: {},
    description: {
      type: 'text' as const,
      items: ['Solve the equation: 2x + 3 = 7'],
    },
  },
  isLoading: false,
  tasks: [],
  isOurPupil: true,
  isStartedToday: false,
  timeLeft: 3600,
  hasTheory: false,
  currentUser: {
    id: 1,
    firstname: 'John',
    surname: 'Doe',
  },
  selectedIndexes: [],
  lockVersion: null,
  characterTexts: {
    yourAnswerIsCorrect: ['Great job!'],
    yourAnswerIsNotCorrect: ['Try again!'],
  },
  selectedCharacter: null,
  lesson: {
    id: 1,
    title: 'Sample Lesson',
  },
  isTheoryHide: false,
  userProgress: 50,
  isReloadPageConfirmationOpen: false,
  isTimeElapsedModalOpen: false,
}

// Mock settings
const mockSettings = {
  lessonId: 1,
  personalStudyItemId: undefined,
  teacherLessonId: undefined,
  selfWorkId: undefined,
  userProgress: 50,
  isNewFreeTasks: false,
  fontSizeFactor: 1,
  socket: {},
  isMobile: 'false',
  appVersion: '1.0.0',
  updateAsCompleted: () => {},
  applicationType: 'web',
  canUseDotNavigation: true,
}

// Mock close modal function
const closeModal = () => {
  console.log('Modal closed')
}

// Mock props
const mockProps: TaskModalProps = {
  deps: mockDependencies,
  state: mockData,
  settings: mockSettings,
  closeModal,
}

const App = () => (
  <div>
    <TaskModal {...mockProps} />
  </div>
)

createRoot(document.getElementById('root')!).render(<App />)
